import peewee

db = peewee.SqliteDatabase('nba_traditional_stats.db')

class playerTraditionalTotalStats(peewee.Model):
    season_id = peewee.CharField(null=True)
    player_id = peewee.IntegerField(null=True)
    player_name = peewee.CharField(null=True)
    team_id = peewee.IntegerField(null=True)
    team_abbreviation = peewee.CharField(null=True)
    age = peewee.IntegerField(null=True)
    gp = peewee.IntegerField(null=True)
    w = peewee.IntegerField(null=True)
    l = peewee.IntegerField(null=True)
    w_pct = peewee.FloatField(null=True)
    min = peewee.FloatField(null=True)
    fgm = peewee.FloatField(null=True)
    fga = peewee.FloatField(null=True)
    fg_pct = peewee.FloatField(null=True)
    fg3m = peewee.FloatField(null=True)
    fg3a = peewee.FloatField(null=True)
    fg3_pct = peewee.FloatField(null=True)
    ftm = peewee.FloatField(null=True)
    fta = peewee.FloatField(null=True)
    ft_pct = peewee.FloatField(null=True)
    oreb = peewee.FloatField(null=True)
    dreb = peewee.FloatField(null=True)
    reb = peewee.FloatField(null=True)
    ast = peewee.FloatField(null=True)
    tov = peewee.FloatField(null=True)
    stl = peewee.FloatField(null=True)
    blk = peewee.FloatField(null=True)
    blka = peewee.FloatField(null=True)
    pf = peewee.FloatField(null=True)
    pfd = peewee.FloatField(null=True)
    pts = peewee.FloatField(null=True)
    plus_minus = peewee.FloatField(null=True)
    nba_fantasy_pts = peewee.FloatField(null=True)
    dd2 = peewee.FloatField(null=True)
    td3 = peewee.FloatField(null=True)
    gp_rank = peewee.IntegerField(null=True)
    w_rank = peewee.IntegerField(null=True)
    l_rank = peewee.IntegerField(null=True)
    w_pct_rank = peewee.IntegerField(null=True)
    min_rank = peewee.IntegerField(null=True)
    fgm_rank = peewee.IntegerField(null=True)
    fga_rank = peewee.IntegerField(null=True)
    fg_pct_rank = peewee.IntegerField(null=True)
    fg3m_rank = peewee.IntegerField(null=True)
    fg3a_rank = peewee.IntegerField(null=True)
    fg3_pct_rank = peewee.IntegerField(null=True)
    ftm_rank = peewee.IntegerField(null=True)
    fta_rank = peewee.IntegerField(null=True)
    ft_pct_rank = peewee.IntegerField(null=True)
    oreb_rank = peewee.IntegerField(null=True)
    dreb_rank = peewee.IntegerField(null=True)
    reb_rank = peewee.IntegerField(null=True)
    ast_rank = peewee.IntegerField(null=True)
    tov_rank = peewee.IntegerField(null=True)
    stl_rank = peewee.IntegerField(null=True)
    blk_rank = peewee.IntegerField(null=True)
    blka_rank = peewee.IntegerField(null=True)
    pf_rank = peewee.IntegerField(null=True)
    pfd_rank = peewee.IntegerField(null=True)
    pts_rank = peewee.IntegerField(null=True)
    plus_minus_rank = peewee.IntegerField(null=True)
    nba_fantasy_pts_rank = peewee.IntegerField(null=True)
    dd2_rank = peewee.IntegerField(null=True)
    td3_rank = peewee.IntegerField(null=True)
    cfid = peewee.IntegerField(null=True)
    cfparams = peewee.CharField(null=True)

    class Meta:
        database = db
        db_table = 'Traditional Totals'